package com.sebulli.fakturama.model;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 *  ###  Generated by EclipseLink Project EclipseLink Workbench 2.4.1 - Wed May 22 11:16:34 CEST 2013.  ###
 */

public class List {

	private String value;
	private String name;
	private boolean deleted;
	private String category;
	@Id
	@GeneratedValue
	private int id;

public List() {
}

public String getCategory() {
	return this.category;
}

public int getId() {
	return this.id;
}

public String getName() {
	return this.name;
}

public String getValue() {
	return this.value;
}

public boolean isDeleted() {
	return this.deleted;
}

public void setCategory(String category) {
	this.category = category;
}

public void setDeleted(boolean deleted) {
	this.deleted = deleted;
}

public void setId(int id) {
	this.id = id;
}

public void setName(String name) {
	this.name = name;
}

public void setValue(String value) {
	this.value = value;
}

}
