package com.sebulli.fakturama.oldmodel;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.eclipse.persistence.annotations.ReadOnly;

/**
 *  ###  Generated by EclipseLink Project EclipseLink Workbench 2.5.1 - Thu Nov 07 21:56:49 CET 2013.  ###
 */

@Entity
@Table(name = "Documents")
@ReadOnly
public class OldDocuments {

	private String consultant;
	private String webshopid;
	private String webshopdate;
	private int transaction;
	private double total;
	private String shippingvatdescription;
	private double shippingvat;
	private String shippingname;
	private int shippingid;
	private String shippingdescription;
	private int shippingautovat;
	private double shipping;
	private String servicedate;
	private int progress;
	private String printedtemplate;
	private boolean printed;
	private String pdfpath;
	private double payvalue;
	private String paymenttext;
	private String paymentname;
	private int paymentid;
	private String paymentdescription;
	private String paydate;
	private boolean paid;
	private String orderdate;
	private String odtpath;
	private String novatname;
	private String novatdescription;
	private boolean novat;
	private String name;
	private String message3;
	private String message2;
	private String message;
	private double itemsdiscount;
	private String items;
	private int invoiceid;
	private int dunninglevel;
	private int duedays;
	private String deliveryaddress;
	private boolean deleted;
	private String date;
	private String customerref;
	private int category;
	private int addressid;
	private String addressfirstline;
	private String address;
	
	@Id
	private int id;

public OldDocuments() {
}

public String getAddress() {
	return this.address;
}

public String getAddressfirstline() {
	return this.addressfirstline;
}

public int getAddressid() {
	return this.addressid;
}

public int getCategory() {
	return this.category;
}

public String getConsultant() {
	return this.consultant;
}

public String getCustomerref() {
	return this.customerref;
}

public String getDate() {
	return this.date;
}

public String getDeliveryaddress() {
	return this.deliveryaddress;
}

public int getDuedays() {
	return this.duedays;
}

public int getDunninglevel() {
	return this.dunninglevel;
}

public int getId() {
	return this.id;
}

public int getInvoiceid() {
	return this.invoiceid;
}

public String getItems() {
	return this.items;
}

public double getItemsdiscount() {
	return this.itemsdiscount;
}

public String getMessage() {
	return this.message;
}

public String getMessage2() {
	return this.message2;
}

public String getMessage3() {
	return this.message3;
}

public String getName() {
	return this.name;
}

public String getNovatdescription() {
	return this.novatdescription;
}

public String getNovatname() {
	return this.novatname;
}

public String getOdtpath() {
	return this.odtpath;
}

public String getOrderdate() {
	return this.orderdate;
}

public String getPaydate() {
	return this.paydate;
}

public String getPaymentdescription() {
	return this.paymentdescription;
}

public int getPaymentid() {
	return this.paymentid;
}

public String getPaymentname() {
	return this.paymentname;
}

public String getPaymenttext() {
	return this.paymenttext;
}

public double getPayvalue() {
	return this.payvalue;
}

public String getPdfpath() {
	return this.pdfpath;
}

public String getPrintedtemplate() {
	return this.printedtemplate;
}

public int getProgress() {
	return this.progress;
}

public String getServicedate() {
	return this.servicedate;
}

public double getShipping() {
	return this.shipping;
}

public int getShippingautovat() {
	return this.shippingautovat;
}

public String getShippingdescription() {
	return this.shippingdescription;
}

public int getShippingid() {
	return this.shippingid;
}

public String getShippingname() {
	return this.shippingname;
}

public double getShippingvat() {
	return this.shippingvat;
}

public String getShippingvatdescription() {
	return this.shippingvatdescription;
}

public double getTotal() {
	return this.total;
}

public int getTransaction() {
	return this.transaction;
}

public String getWebshopdate() {
	return this.webshopdate;
}

public String getWebshopid() {
	return this.webshopid;
}

public boolean isDeleted() {
	return this.deleted;
}

public boolean isNovat() {
	return this.novat;
}

public boolean isPaid() {
	return this.paid;
}

public boolean isPrinted() {
	return this.printed;
}

public void setAddress(String address) {
	this.address = address;
}

public void setAddressfirstline(String addressfirstline) {
	this.addressfirstline = addressfirstline;
}

public void setAddressid(int addressid) {
	this.addressid = addressid;
}

public void setCategory(int category) {
	this.category = category;
}

public void setConsultant(String consultant) {
	this.consultant = consultant;
}

public void setCustomerref(String customerref) {
	this.customerref = customerref;
}

public void setDate(String date) {
	this.date = date;
}

public void setDeleted(boolean deleted) {
	this.deleted = deleted;
}

public void setDeliveryaddress(String deliveryaddress) {
	this.deliveryaddress = deliveryaddress;
}

public void setDuedays(int duedays) {
	this.duedays = duedays;
}

public void setDunninglevel(int dunninglevel) {
	this.dunninglevel = dunninglevel;
}

public void setId(int id) {
	this.id = id;
}

public void setInvoiceid(int invoiceid) {
	this.invoiceid = invoiceid;
}

public void setItems(String items) {
	this.items = items;
}

public void setItemsdiscount(double itemsdiscount) {
	this.itemsdiscount = itemsdiscount;
}

public void setMessage(String message) {
	this.message = message;
}

public void setMessage2(String message2) {
	this.message2 = message2;
}

public void setMessage3(String message3) {
	this.message3 = message3;
}

public void setName(String name) {
	this.name = name;
}

public void setNovat(boolean novat) {
	this.novat = novat;
}

public void setNovatdescription(String novatdescription) {
	this.novatdescription = novatdescription;
}

public void setNovatname(String novatname) {
	this.novatname = novatname;
}

public void setOdtpath(String odtpath) {
	this.odtpath = odtpath;
}

public void setOrderdate(String orderdate) {
	this.orderdate = orderdate;
}

public void setPaid(boolean paid) {
	this.paid = paid;
}

public void setPaydate(String paydate) {
	this.paydate = paydate;
}

public void setPaymentdescription(String paymentdescription) {
	this.paymentdescription = paymentdescription;
}

public void setPaymentid(int paymentid) {
	this.paymentid = paymentid;
}

public void setPaymentname(String paymentname) {
	this.paymentname = paymentname;
}

public void setPaymenttext(String paymenttext) {
	this.paymenttext = paymenttext;
}

public void setPayvalue(double payvalue) {
	this.payvalue = payvalue;
}

public void setPdfpath(String pdfpath) {
	this.pdfpath = pdfpath;
}

public void setPrinted(boolean printed) {
	this.printed = printed;
}

public void setPrintedtemplate(String printedtemplate) {
	this.printedtemplate = printedtemplate;
}

public void setProgress(int progress) {
	this.progress = progress;
}

public void setServicedate(String servicedate) {
	this.servicedate = servicedate;
}

public void setShipping(double shipping) {
	this.shipping = shipping;
}

public void setShippingautovat(int shippingautovat) {
	this.shippingautovat = shippingautovat;
}

public void setShippingdescription(String shippingdescription) {
	this.shippingdescription = shippingdescription;
}

public void setShippingid(int shippingid) {
	this.shippingid = shippingid;
}

public void setShippingname(String shippingname) {
	this.shippingname = shippingname;
}

public void setShippingvat(double shippingvat) {
	this.shippingvat = shippingvat;
}

public void setShippingvatdescription(String shippingvatdescription) {
	this.shippingvatdescription = shippingvatdescription;
}

public void setTotal(double total) {
	this.total = total;
}

public void setTransaction(int transaction) {
	this.transaction = transaction;
}

public void setWebshopdate(String webshopdate) {
	this.webshopdate = webshopdate;
}

public void setWebshopid(String webshopid) {
	this.webshopid = webshopid;
}

}
