package com.sebulli.fakturama.oldmodel;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.eclipse.persistence.annotations.ReadOnly;

/**
 *  ###  Generated by EclipseLink Project EclipseLink Workbench 2.5.1 - Thu Nov 07 21:56:49 CET 2013.  ###
 */

@Entity
@Table(name = "Expenditures")
@ReadOnly
public class OldExpenditures {

	private double total;
	private double paid;
	private String nr;
	private String name;
	private String items;
	private boolean donotbook;
	private String documentnr;
	private boolean discounted;
	private boolean deleted;
	private String date;
	private String category;
	@Id
	private int id;

public OldExpenditures() {
}

public String getCategory() {
	return this.category;
}

public String getDate() {
	return this.date;
}

public String getDocumentnr() {
	return this.documentnr;
}

public int getId() {
	return this.id;
}

public String getItems() {
	return this.items;
}

public String getName() {
	return this.name;
}

public String getNr() {
	return this.nr;
}

public double getPaid() {
	return this.paid;
}

public double getTotal() {
	return this.total;
}

public boolean isDeleted() {
	return this.deleted;
}

public boolean isDiscounted() {
	return this.discounted;
}

public boolean isDonotbook() {
	return this.donotbook;
}

public void setCategory(String category) {
	this.category = category;
}

public void setDate(String date) {
	this.date = date;
}

public void setDeleted(boolean deleted) {
	this.deleted = deleted;
}

public void setDiscounted(boolean discounted) {
	this.discounted = discounted;
}

public void setDocumentnr(String documentnr) {
	this.documentnr = documentnr;
}

public void setDonotbook(boolean donotbook) {
	this.donotbook = donotbook;
}

public void setId(int id) {
	this.id = id;
}

public void setItems(String items) {
	this.items = items;
}

public void setName(String name) {
	this.name = name;
}

public void setNr(String nr) {
	this.nr = nr;
}

public void setPaid(double paid) {
	this.paid = paid;
}

public void setTotal(double total) {
	this.total = total;
}

}
