package com.sebulli.fakturama.oldmodel;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.eclipse.persistence.annotations.ReadOnly;

/**
 *  ###  Generated by EclipseLink Project EclipseLink Workbench 2.5.1 - Thu Nov 07 21:56:49 CET 2013.  ###
 */

@Entity
@Table(name = "Items")
@ReadOnly
public class OldItems {

	@Id
	private int id;
	private double vatvalue;
	private String vatname;
	private int vatid;
	private String vatdescription;
	
	/**
	 * The "shared" attribute was used formerly to share Items between more than one Document.
	 * If a Document was copied, the items were "shared" initially. Only if an item was changed,
	 * the "shared" status changed from <code>true</code> to <code>false</code>. I think it's
	 * better to copy <i>all</i> Items if a Document is copied. Then we don't have to handle
	 * any extra status for Items. Therefore this attribute is only for migration purposes.
	 * 
	 * @deprecated
	 */
	private boolean shared;
	private String qunit;
	private double quantity;
	private int productid;
	private double price;
	private String picturename;
	private int owner;
	private boolean optional;
	private boolean novat;
	private String name;
	private String itemnr;
	private double discount;
	private String description;
	private boolean deleted;
	private String category;
	
	// these attributes are only available in the PRO version!
//	private double weight;
//	private double tara;

public OldItems() {
}

public String getCategory() {
	return this.category;
}

public String getDescription() {
	return this.description;
}

public double getDiscount() {
	return this.discount;
}

public int getId() {
	return this.id;
}

public String getItemnr() {
	return this.itemnr;
}

public String getName() {
	return this.name;
}

public int getOwner() {
	return this.owner;
}

public String getPicturename() {
	return this.picturename;
}

public double getPrice() {
	return this.price;
}

public int getProductid() {
	return this.productid;
}

public double getQuantity() {
	return this.quantity;
}

public String getQunit() {
	return this.qunit;
}

public String getVatdescription() {
	return this.vatdescription;
}

public int getVatid() {
	return this.vatid;
}

public String getVatname() {
	return this.vatname;
}

public double getVatvalue() {
	return this.vatvalue;
}

/* only PRO version!!!
public double getTara() {
	return this.tara;
}

public double getWeight() {
	return this.weight;
}

public void setTara(double tara) {
	this.tara = tara;
}

public void setWeight(double weight) {
	this.weight = weight;
}
*/
public boolean isDeleted() {
	return this.deleted;
}

public boolean isNovat() {
	return this.novat;
}

public boolean isOptional() {
	return this.optional;
}


/**
 * The "shared" attribute was used formerly to share Items between more than one Document.
 * If a Document was copied, the items were "shared" initially. Only if an item was changed,
 * the "shared" status changed from <code>true</code> to <code>false</code>. I think it's
 * better to copy <i>all</i> Items if a Document is copied. Then we don't have to handle
 * any extra status for Items. Therefore this attribute is only for migration purposes.
 * 
 * @deprecated
 */
public boolean isShared() {
	return this.shared;
}

public void setCategory(String category) {
	this.category = category;
}

public void setDeleted(boolean deleted) {
	this.deleted = deleted;
}

public void setDescription(String description) {
	this.description = description;
}

public void setDiscount(double discount) {
	this.discount = discount;
}

public void setId(int id) {
	this.id = id;
}

public void setItemnr(String itemnr) {
	this.itemnr = itemnr;
}

public void setName(String name) {
	this.name = name;
}

public void setNovat(boolean novat) {
	this.novat = novat;
}

public void setOptional(boolean optional) {
	this.optional = optional;
}

public void setOwner(int owner) {
	this.owner = owner;
}

public void setPicturename(String picturename) {
	this.picturename = picturename;
}

public void setPrice(double price) {
	this.price = price;
}

public void setProductid(int productid) {
	this.productid = productid;
}

public void setQuantity(double quantity) {
	this.quantity = quantity;
}

public void setQunit(String qunit) {
	this.qunit = qunit;
}


/**
 * The "shared" attribute was used formerly to share Items between more than one Document.
 * If a Document was copied, the items were "shared" initially. Only if an item was changed,
 * the "shared" status changed from <code>true</code> to <code>false</code>. I think it's
 * better to copy <i>all</i> Items if a Document is copied. Then we don't have to handle
 * any extra status for Items. Therefore this attribute is only for migration purposes.
 * 
 * @deprecated
 */
public void setShared(boolean shared) {
	this.shared = shared;
}

public void setVatdescription(String vatdescription) {
	this.vatdescription = vatdescription;
}

public void setVatid(int vatid) {
	this.vatid = vatid;
}

public void setVatname(String vatname) {
	this.vatname = vatname;
}

public void setVatvalue(double vatvalue) {
	this.vatvalue = vatvalue;
}

}
