package com.sebulli.fakturama.oldmodel;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.eclipse.persistence.annotations.ReadOnly;

/**
 *  ###  Generated by EclipseLink Project EclipseLink Workbench 2.4.1 - Wed May 22 11:16:34 CEST 2013.  ###
 */
@Entity
@Table(name = "Shippings")
@ReadOnly
public class OldShippings {

	// calculate the shipping's vat with a fix vat value
	public static final int SHIPPINGVATFIX = 0;
	// calculate the shipping's vat with the same vat of the items. The shipping vat is a gross value.
	public static final int SHIPPINGVATGROSS = 1;
	// calculate the shipping's vat with the same vat of the items. The shipping vat is a net value.
	public static final int SHIPPINGVATNET = 2;

	private int vatid;
	private double value;
	private String name;
	private String description;
	private boolean deleted;
	private String category;
	private int autovat;
	
	@Id
	private int id;

public int getAutovat() {
	return this.autovat;
}

public String getCategory() {
	return this.category;
}

public String getDescription() {
	return this.description;
}

public int getId() {
	return this.id;
}

public String getName() {
	return this.name;
}

public double getValue() {
	return this.value;
}

public int getVatid() {
	return this.vatid;
}

public boolean isDeleted() {
	return this.deleted;
}

public void setAutovat(int autovat) {
	this.autovat = autovat;
}

public void setCategory(String category) {
	this.category = category;
}

public void setDeleted(boolean deleted) {
	this.deleted = deleted;
}

public void setDescription(String description) {
	this.description = description;
}

public void setId(int id) {
	this.id = id;
}

public void setName(String name) {
	this.name = name;
}

public void setValue(double value) {
	this.value = value;
}

public void setVatid(int vatid) {
	this.vatid = vatid;
}

}
